import { z } from "zod"
import {
  CONFIDENCE_LEVELS,
  CONSISTENCY_VALUES,
  RELIABILITY_GRADES,
} from "@/lib/exercises/scales"

/**
 * Practical exercise schema.
 *
 * An exercise is a fictional brief pack (scenario + several reports) plus an
 * expert answer key. The answer key never leaves the server for library
 * exercises — the client only ever receives the student view (see
 * `toStudentView`). Exercises are plain JSON-shaped data so they can be
 * authored by hand, generated by The Chief, or pushed by an n8n workflow.
 */

const LEVELS = ["Beginner", "Intermediate", "Advanced"] as const
export type ExerciseLevel = (typeof LEVELS)[number]
export const EXERCISE_LEVELS = LEVELS

const keywordList = z.array(z.string().min(2).max(40)).min(1).max(24)

export const expectedGradeSchema = z.object({
  reliability: z.enum(RELIABILITY_GRADES),
  credibility: z.number().int().min(1).max(6),
  /** Grades a trained analyst could defensibly give. Scored as "close". */
  acceptableReliability: z.array(z.enum(RELIABILITY_GRADES)).max(6).optional(),
  acceptableCredibility: z.array(z.number().int().min(1).max(6)).max(6).optional(),
  rationale: z.string().min(10).max(900),
  flags: z.array(z.string().min(3).max(260)).max(5).optional(),
})

export const reportSchema = z.object({
  id: z.string().regex(/^R\d{1,2}$/),
  title: z.string().min(3).max(140),
  /** Short category label: "Official record", "Human source", "Open source"… */
  sourceType: z.string().min(3).max(60),
  /** What the student knows about the source — enough to grade reliability. */
  source: z.string().min(10).max(500),
  dateTime: z.string().min(2).max(60),
  body: z.string().min(20).max(2600),
  expected: expectedGradeSchema,
})

export const gapSchema = z.object({
  id: z.string().regex(/^G\d{1,2}$/),
  gap: z.string().min(5).max(300),
  whyItMatters: z.string().min(5).max(500),
  collection: z.string().min(5).max(500),
  /** Lower-case fragments; a student gap matches when ≥ minMatches appear. */
  keywords: keywordList,
  minMatches: z.number().int().min(1).max(4).optional(),
})

export const hypothesisSchema = z.object({
  id: z.string().regex(/^H\d$/),
  statement: z.string().min(5).max(400),
  kind: z.enum(["lead", "alternative", "null"]).optional(),
  keywords: keywordList,
  minMatches: z.number().int().min(1).max(4).optional(),
  /** Expert ACH matrix: report id → C / I / N. */
  matrix: z.record(z.string().regex(/^R\d{1,2}$/), z.enum(CONSISTENCY_VALUES)),
  assessment: z.string().min(5).max(700),
})

export const keyJudgmentSchema = z.object({
  statement: z.string().min(5).max(700),
  confidence: z.enum(CONFIDENCE_LEVELS),
})

export const modelAnswerSchema = z.object({
  bluf: z.string().min(20).max(1500),
  /**
   * The substance a good BLUF / key judgments must engage with — checked by
   * keyword. Falls back to the lead hypothesis when absent.
   */
  mustAddress: z
    .object({ label: z.string().min(5).max(200), keywords: keywordList })
    .optional(),
  keyJudgments: z.array(keyJudgmentSchema).min(1).max(5),
  gaps: z.array(gapSchema).min(2).max(8),
  hypotheses: z.array(hypothesisSchema).min(2).max(5),
  indicators: z.array(z.string().min(5).max(400)).min(1).max(8),
  commonMistakes: z.array(z.string().min(5).max(400)).min(1).max(8),
  teachingPoints: z.array(z.string().min(5).max(400)).min(1).max(6),
})

export const scenarioSchema = z.object({
  setting: z.string().min(20).max(2000),
  requester: z.string().min(3).max(200),
  keyQuestion: z.string().min(10).max(400),
  deadline: z.string().min(3).max(200),
})

export const exerciseSchema = z.object({
  slug: z.string().regex(/^[a-z0-9-]{3,80}$/),
  title: z.string().min(3).max(120),
  level: z.enum(LEVELS),
  domain: z.string().min(3).max(60),
  estimatedMinutes: z.number().int().min(5).max(120),
  skills: z.array(z.string().min(3).max(60)).min(1).max(6),
  summary: z.string().min(20).max(400),
  scenario: scenarioSchema,
  reports: z.array(reportSchema).min(3).max(10),
  modelAnswer: modelAnswerSchema,
  relatedLessons: z.array(z.string().regex(/^\/topics\/[a-z0-9-]+$/)).max(8),
  /** True for exercises The Chief generated on demand (not part of the library). */
  generated: z.boolean().optional(),
})

export type Exercise = z.infer<typeof exerciseSchema>
export type ExerciseReport = z.infer<typeof reportSchema>
export type ExpectedGrade = z.infer<typeof expectedGradeSchema>
export type ExerciseGap = z.infer<typeof gapSchema>
export type ExerciseHypothesis = z.infer<typeof hypothesisSchema>
export type ModelAnswer = z.infer<typeof modelAnswerSchema>

export type StudentReport = Omit<ExerciseReport, "expected">
export type ExerciseStudentView = Omit<Exercise, "reports" | "modelAnswer"> & {
  reports: StudentReport[]
}

/** Strip the answer key. This is all a library exercise ever sends to the browser. */
export function toStudentView(exercise: Exercise): ExerciseStudentView {
  const { modelAnswer: _answer, reports, ...rest } = exercise
  return {
    ...rest,
    reports: reports.map(({ expected: _expected, ...report }) => report),
  }
}

/**
 * Cross-field checks zod can't express. Returns a list of problems
 * (empty = valid). Used by tests for library exercises and at runtime
 * for exercises The Chief generates.
 */
export function checkExerciseIntegrity(exercise: Exercise): string[] {
  const problems: string[] = []
  const reportIds = exercise.reports.map((r) => r.id)
  const reportSet = new Set(reportIds)
  if (reportSet.size !== reportIds.length) problems.push("Duplicate report ids")

  const gapIds = exercise.modelAnswer.gaps.map((g) => g.id)
  if (new Set(gapIds).size !== gapIds.length) problems.push("Duplicate gap ids")

  const hypIds = exercise.modelAnswer.hypotheses.map((h) => h.id)
  if (new Set(hypIds).size !== hypIds.length) problems.push("Duplicate hypothesis ids")

  for (const h of exercise.modelAnswer.hypotheses) {
    for (const key of Object.keys(h.matrix)) {
      if (!reportSet.has(key)) problems.push(`${h.id} matrix references unknown report ${key}`)
    }
    for (const id of reportIds) {
      if (!h.matrix[id]) problems.push(`${h.id} matrix is missing ${id}`)
    }
  }

  for (const r of exercise.reports) {
    const e = r.expected
    if (e.acceptableReliability && !e.acceptableReliability.includes(e.reliability)) {
      problems.push(`${r.id} acceptableReliability should include the expected grade ${e.reliability}`)
    }
    if (e.acceptableCredibility && !e.acceptableCredibility.includes(e.credibility)) {
      problems.push(`${r.id} acceptableCredibility should include the expected grade ${e.credibility}`)
    }
  }

  for (const g of exercise.modelAnswer.gaps) {
    if ((g.minMatches ?? 1) > g.keywords.length) problems.push(`${g.id} minMatches exceeds keyword count`)
  }
  for (const h of exercise.modelAnswer.hypotheses) {
    if ((h.minMatches ?? 1) > h.keywords.length) problems.push(`${h.id} minMatches exceeds keyword count`)
  }
  return problems
}

// ---------------------------------------------------------------------------
// Student submission
// ---------------------------------------------------------------------------

const reliabilityAnswer = z.union([z.enum(RELIABILITY_GRADES), z.literal("")])
const consistencyAnswer = z.union([z.enum(CONSISTENCY_VALUES), z.literal("")])
const confidenceAnswer = z.union([z.enum(CONFIDENCE_LEVELS), z.literal("")])

export const submissionSchema = z.object({
  evaluations: z
    .array(
      z.object({
        reportId: z.string().max(8),
        reliability: reliabilityAnswer,
        credibility: z.number().int().min(0).max(6),
        note: z.string().max(600),
      }),
    )
    .max(12),
  gaps: z.array(z.string().max(400)).max(10),
  hypotheses: z
    .array(
      z.object({
        statement: z.string().max(400),
        ratings: z.record(z.string().max(8), consistencyAnswer),
      }),
    )
    .max(6),
  assessment: z.object({
    bluf: z.string().max(1500),
    keyJudgments: z
      .array(z.object({ statement: z.string().max(700), confidence: confidenceAnswer }))
      .max(6),
    indicators: z.string().max(2000),
    reasoning: z.string().max(4000),
  }),
})

export type ExerciseSubmission = z.infer<typeof submissionSchema>

export { emptySubmission } from "@/lib/exercises/blank"

/** Drop blank rows before scoring or sending to a model. */
export function cleanSubmission(sub: ExerciseSubmission): ExerciseSubmission {
  return {
    evaluations: sub.evaluations.map((e) => ({ ...e, note: e.note.trim() })),
    gaps: sub.gaps.map((g) => g.trim()).filter(Boolean),
    hypotheses: sub.hypotheses
      .map((h) => ({ ...h, statement: h.statement.trim() }))
      .filter((h) => h.statement.length > 0),
    assessment: {
      bluf: sub.assessment.bluf.trim(),
      keyJudgments: sub.assessment.keyJudgments
        .map((k) => ({ ...k, statement: k.statement.trim() }))
        .filter((k) => k.statement.length > 0),
      indicators: sub.assessment.indicators.trim(),
      reasoning: sub.assessment.reasoning.trim(),
    },
  }
}
